title: Roman Kosobrodov
email: your-email@domain.com
description: > 
   Roman Kosobrodov - software developer web site
baseurl: "" 
url: "http://romankosobrodov.github.com" 
linkedin_username: kosobrodov
github_username:  romankosobrodov

markdown: kramdown

highlighter: pygments

paginate: 15
paginate_path: "/blog/page:num/"

